In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

age          job   marital  education default  balance housing loan  \
0      38   technician   married   tertiary      no      127     yes   no   
1      41    housemaid   married    primary      no      365      no   no   
2      39   management    single   tertiary      no     2454     yes   no   
3      49  blue-collar   married    primary      no     6215     yes   no   
4      37     services   married  secondary      no     1694     yes  yes   
...   ...          ...       ...        ...     ...      ...     ...  ...   
8366   52   management   married   tertiary      no      388      no   no   
8367   39     services   married  secondary      no     2758      no   no   
8368   38  blue-collar   married    primary      no      178     yes   no   
8369   59      retired  divorced    unknown      no      -49     yes   no   
8370   41  blue-collar  divorced    primary      no        0      no   no   

       contact  day month  duration  campaign  pdays  previous poutcome  \
0     cellular   14   oct       113         1     50         2  success   
1     cellular    8   aug       203         5     -1         0  unknown   
2     cellular    4   may       716         3    263         2  failure   
3     cellular   11   may       549         1     -1         0  unknown   
4     cellular   29   jan       404         2    251         6  failure   
...        ...  ...   ...       ...       ...    ...       ...      ...   
8366  cellular   25   may       272         1     -1         0  unknown   
8367  cellular    4   feb       658         3     -1         0  unknown   
8368   unknown   20   may       245         1     -1         0  unknown   
8369   unknown   13   may       248         2     -1         0  unknown   
8370  cellular   30   jul       509         2     -1         0  unknown   

     deposit  
0         no  
1         no  
2        yes  
3         no  
4         no  
...      ...  
8366     yes  
8367     yes  
8368      no  
8369      no  
8370     yes  

[8371 rows x 17 columns]

In [4]:
def job_to_num(x):
        if x=='admin': return 12
        if x=='student': return 11
        if x=='unknown': return 10
        if x=='unemployed': return 9
        if x=='services': return 8
        if x=='self-employed': return 7
        if x=='retired': return 6
        if x=='entrepreneur': return 5
        if x=='blue-collar': return 4
        if x=='management': return 3
        if x=='technician': return 2
        if x=='housemaid':   return 1
        else: return 0
        
        
def marital_to_num(x):
    if x=='divorced': return 4
    if x=='married': return 3
    if x=='single': return 2
    if x=='unknown': return 1
    else: return 0


def education_to_num(x):
    if x=='tertiary': return 11
    if x=='secondary': return 10
    if x=='primary': return 9
    if x=='unknown': return 8
    if x=='university.degree': return 7
    if x=='professional.course': return 6
    if x=='illiterate': return 5
    if x=='high.school': return 4
    if x=='basic.9y': return 3
    if x=='basic.6y': return 2
    if x=='basic.4y': return 1
    else: return 0


def default_to_num(x):
    if x=='no': return 2
    if x=='yes': return 1
    else: return 0


def housing_to_num(x):
    if x=='no': return 2
    if x=='yes': return 1
    else: return 0

def loan_to_num(x):
    if x=='no': return 2
    if x=='yes': return 1
    else: return 0

def contact_to_num(x):
    if x=='cellular': return 2
    if x=='telephone': return 1
    else: return 0

def month_to_num(x):
    if x=='dec': return 12
    if x=='nov': return 11
    if x=='oct': return 10
    if x=='sep': return 9
    if x=='aug': return 8
    if x=='jul': return 7
    if x=='jun': return 6
    if x=='may': return 5
    if x=='apr': return 4
    if x=='mar': return 3
    if x=='feb': return 2
    if x=='jan': return 1
    else: return 0

def poutcome_to_num(x):
    if x=='failure': return 2
    if x=='success': return 1
    else: return 0

def deposit_to_num(x):
    if x=='no': return 2
    if x=='yes': return 1
    else: return 0

In [5]:
df['job_num'] = df['job'].apply(job_to_num)
df['marital_num'] = df['marital'].apply(marital_to_num)
df['education_num'] = df['education'].apply(education_to_num)
df['default_num'] = df['default'].apply(default_to_num)
df['housing_num'] = df['housing'].apply(housing_to_num)
df['loan_num'] = df['loan'].apply(loan_to_num)
df['contact_num'] = df['contact'].apply(contact_to_num)
df['month_num'] = df['month'].apply(month_to_num)
df['poutcome_num'] = df['poutcome'].apply(poutcome_to_num)
df['deposit_num'] = df['deposit'].apply(deposit_to_num)
df

age          job   marital  education default  balance housing loan  \
0      38   technician   married   tertiary      no      127     yes   no   
1      41    housemaid   married    primary      no      365      no   no   
2      39   management    single   tertiary      no     2454     yes   no   
3      49  blue-collar   married    primary      no     6215     yes   no   
4      37     services   married  secondary      no     1694     yes  yes   
...   ...          ...       ...        ...     ...      ...     ...  ...   
8366   52   management   married   tertiary      no      388      no   no   
8367   39     services   married  secondary      no     2758      no   no   
8368   38  blue-collar   married    primary      no      178     yes   no   
8369   59      retired  divorced    unknown      no      -49     yes   no   
8370   41  blue-collar  divorced    primary      no        0      no   no   

       contact  day  ... job_num  marital_num  education_num  default_num  \
0     cellular   14  ...       2            3             11            2   
1     cellular    8  ...       1            3              9            2   
2     cellular    4  ...       3            2             11            2   
3     cellular   11  ...       4            3              9            2   
4     cellular   29  ...       8            3             10            2   
...        ...  ...  ...     ...          ...            ...          ...   
8366  cellular   25  ...       3            3             11            2   
8367  cellular    4  ...       8            3             10            2   
8368   unknown   20  ...       4            3              9            2   
8369   unknown   13  ...       6            4              8            2   
8370  cellular   30  ...       4            4              9            2   

      housing_num loan_num contact_num  month_num  poutcome_num  deposit_num  
0               1        2           2         10             1            2  
1               2        2           2          8             0            2  
2               1        2           2          5             2            1  
3               1        2           2          5             0            2  
4               1        1           2          1             2            2  
...           ...      ...         ...        ...           ...          ...  
8366            2        2           2          5             0            1  
8367            2        2           2          2             0            1  
8368            1        2           0          5             0            2  
8369            1        2           0          5             0            2  
8370            2        2           2          7             0            1  

[8371 rows x 27 columns]

In [6]:
df.drop(['job','marital','education','default','housing','loan','contact','month','poutcome','deposit'], axis=1, inplace=True)
#df.drop(['day'], axis=1, inplace=True)
df

age  balance  day  duration  campaign  pdays  previous  job_num  \
0      38      127   14       113         1     50         2        2   
1      41      365    8       203         5     -1         0        1   
2      39     2454    4       716         3    263         2        3   
3      49     6215   11       549         1     -1         0        4   
4      37     1694   29       404         2    251         6        8   
...   ...      ...  ...       ...       ...    ...       ...      ...   
8366   52      388   25       272         1     -1         0        3   
8367   39     2758    4       658         3     -1         0        8   
8368   38      178   20       245         1     -1         0        4   
8369   59      -49   13       248         2     -1         0        6   
8370   41        0   30       509         2     -1         0        4   

      marital_num  education_num  default_num  housing_num  loan_num  \
0               3             11            2            1         2   
1               3              9            2            2         2   
2               2             11            2            1         2   
3               3              9            2            1         2   
4               3             10            2            1         1   
...           ...            ...          ...          ...       ...   
8366            3             11            2            2         2   
8367            3             10            2            2         2   
8368            3              9            2            1         2   
8369            4              8            2            1         2   
8370            4              9            2            2         2   

      contact_num  month_num  poutcome_num  deposit_num  
0               2         10             1            2  
1               2          8             0            2  
2               2          5             2            1  
3               2          5             0            2  
4               2          1             2            2  
...           ...        ...           ...          ...  
8366            2          5             0            1  
8367            2          2             0            1  
8368            0          5             0            2  
8369            0          5             0            2  
8370            2          7             0            1  

[8371 rows x 17 columns]

In [7]:
x=df.iloc[:,:-1].values
y=df.iloc[:,16:].values
x,y

(array([[  38,  127,   14, ...,    2,   10,    1],
        [  41,  365,    8, ...,    2,    8,    0],
        [  39, 2454,    4, ...,    2,    5,    2],
        ...,
        [  38,  178,   20, ...,    0,    5,    0],
        [  59,  -49,   13, ...,    0,    5,    0],
        [  41,    0,   30, ...,    2,    7,    0]], dtype=int64),
 array([[2],
        [2],
        [1],
        ...,
        [2],
        [2],
        [1]], dtype=int64))

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state=0)
y_train

array([[2],
       [1],
       [1],
       ...,
       [1],
       [1],
       [2]], dtype=int64)

In [9]:
lr=LogisticRegression()
lr.fit(x_train,y_train)

C:\Anaconda\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [10]:
y_pred=lr.predict(x_test)
y_pred

array([2, 2, 1, ..., 2, 1, 1], dtype=int64)

In [11]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[529, 247],
       [154, 745]], dtype=int64)

In [12]:
lr.score(x_test, y_test)
print("Logistic Regression Test Accuracy {:.2f}%".format(lr.score(x_test, y_test)*100))

Logistic Regression Test Accuracy 76.06%


In [13]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)
print("Decision Tree Test Accuracy {:.2f}%".format(dtc.score(x_test, y_test)*100))

Decision Tree Test Accuracy 78.21%


In [17]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000, random_state = 1)
rf.fit(x_train, y_train.ravel())
my_prediction=rf.predict(x_test)
my_prediction
print("Random Forest Algorithm Accuracy Score : {:.2f}%".format(rf.score(x_test,y_test)*100))

Random Forest Algorithm Accuracy Score : 84.24%


In [15]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train.ravel())
print("Naive Bayes Test Accuracy {:.2f}%".format(nb.score(x_test, y_test)*100))

Naive Bayes Test Accuracy 75.70%


In [19]:
prediction_df = pd.DataFrame(my_prediction)
prediction_df

0
0     1
1     2
2     1
3     1
4     1
...  ..
1670  2
1671  2
1672  2
1673  1
1674  1

[1675 rows x 1 columns]

In [20]:
compression_opts = dict(method='zip',
                        archive_name='out.csv')  
prediction_df.to_csv('prediction.zip', index=False,
          compression=compression_opts)  